scrape_configs:
  - job_name: 'gradio_app'
    static_configs:
      - targets: ['group3_app:8000']  # Replace IP with container name
  - job_name: 'node_exporter_gradio'
    static_configs:
      - targets: ['group3_app:9100']  # Replace IP with container name
